version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10 # Invoke the Heroku orb

jobs:
  HEROKU-NODEJS-DEPLOY:
    docker:
      - image: "circleci/node:12.9.1-browsers"
    working_directory: ~/realestate
    steps:
      - checkout
      - setup_remote_docker

      # - restore_cache:
      #     key: 'v1-dependencies-{{ checksum "package.json" }}'

      - run:
          name: Install npm modules
          command: |
            cd NODEJS_CODE_BASE
            npm ci

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: 'v1-dependencies-{{ checksum "package.json" }}'

      - run:
          name: Deploy to heroku
          command: |
            git config user.email "shubhamagarwal1694@gmail.com"
            git config user.name "Shubham Agarwal"
            cd NODEJS_CODE_BASE
            ls
            git init
            # git remote set-url origin https://git.heroku.com/github-realestate.git
            git remote set-url origin https://git.heroku.com/$HEROKU_APP_NAME.git
            # git:remote -a $HEROKU_APP_NAME
            git add -f .
            git commit -am "heroku commit"
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $CIRCLE_BRANCH:master

      # - heroku/deploy-via-git:
      #     force: true

workflows:
  version: 2
  REALESTATE-DEPLOY:
    jobs:
      - HEROKU-NODEJS-DEPLOY
        # filters:
        #   branches:
        #     only:
        #       - release/node.*
