version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10 # Invoke the Heroku orb

jobs:
  HEROKU-NODEJS-DEPLOY:
    working_directory: ~/realestate
    docker:
      - image: "circleci/node:12.9.1-browsers"
    steps:
      - checkout
      - setup_remote_docker

      # - restore_cache:
      #     key: 'v1-dependencies-{{ checksum "package.json" }}'

      - run:
          name: Install npm modules
          command: |
            cd NODEJS_CODE_BASE
            ls
            npm ci

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: 'v1-dependencies-{{ checksum "package.json" }}'

      - heroku/deploy-via-git:
          force: true
      # - run:
      #     environment:
      #       HEROKU_APP: "sleepy-refuge-55486"
      #     name: Deploy to heroku
      #     command: |
      #       echo "working"

workflows:
  version: 2
  REALESTATE-DEPLOY:
    jobs:
      - HEROKU-NODEJS-DEPLOY
        # filters:
        #   branches:
        #     only:
        #       - release/node.*
